name: unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++-9, g++-10, g++-11, clang++-11, clang++-12, clang++-13, clang++-14, clang++-15]
        build: [Release, Debug]
    env:
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake git ${{ matrix.cxx }} 

    - name: Install Gtest
      run: |
        git clone https://github.com/google/googletest.git && cd googletest
        mkdir build && cd build
        cmake -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig
    - name: run cmake
      run: |
        mkdir build && cd build
        cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.build }} ..
    - name: build
      run: |
        cd build
        make -j$(nproc)
    - name: run tests
      run: ./build/Test/Tests --gtest_color=yes
