name: unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++-9, g++-10, g++-11, clang++-9, clang++-10, clang++-11, clang++-12, clang++-13, clang++-14, clang++-15]
        build: [Release, Debug]
    env:
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        chmod +x Test/install_deps_ci.sh
        ./Test/install_deps_ci.sh

    - name: Install Gtest
      run: |
        git clone https://github.com/google/googletest.git && cd googletest
        mkdir build && cd build
        cmake -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig
    - name: run cmake
      run: |
        mkdir build && cd build
        cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.build }} ..
    - name: build and run
      run: |
        chmod +x Test/build_and_run_tests_ci.sh
        cd build
        ../Test/build_and_run_tests_ci.sh
